version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: website
    ports:
      - "5173:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    build:
      context: .
      dockerfile: Dockerfile
    # env_file:
    #   - .env
